require("packer_init")

require("core/settings")
require("core/keymaps")
require("core/colors")

require("plugins/feline")
require("plugins/gitsigns-nvim")
require("plugins/null-ls")
require("plugins/nvim-tree")
require("plugins/nvim-treesitter")
require("plugins/mason")
require("plugins/nvim-cmp")
require("plugins/nvim-autopairs")
require("plugins/trouble")
require("plugins/which-key")
